seims/SEIMS

README.md
=> modification test

doc/Developers.md, preprocess/main.py
git fetch upstream <branch>
> git fetch upstream master
@gaohr  @liujunzhi321 @Shenfang1993
=> fetch远程库时最好加上分支名

src/base/module_setting/ModuleFactory.cpp, src/base/util/text.h, src/main/ModulesIOList/ModulesIOList.cpp, src/modules/hydrology/CH_DW/api.cpp, src/modules/hydrology_longterm/DEP_LINSLEY/api.cpp, src/modules/hydrology_longterm/PET_H/api.cpp, src/modules/hydrology_longterm/PET_PM/api.cpp, src/modules/hydrology_longterm/PET_PT/api.cpp
详细参见https://github.com/seims/SEIMS/issues/41
=> add variable, units, and description DEFINITION in text.h

doc/TODO.md, src/base/util/text.h, src/modules/hydrology_longterm/GWA_RE/api.cpp, src/modules/hydrology_longterm/PER_PI/PER_PI.cpp, src/modules/hydrology_longterm/PER_PI/api.cpp, src/modules/hydrology_longterm/PER_STR/PER_STR.cpp, src/modules/hydrology_longterm/PER_STR/api.cpp, src/modules/hydrology_longterm/PI_MSM/api.cpp, src/modules/hydrology_longterm/PI_MSM/clsPI_MSM.cpp, src/modules/hydrology_longterm/SET_LM/SET_LM.cpp, src/modules/hydrology_longterm/SET_LM/api.cpp, src/modules/hydrology_longterm/SNO_DD/SNO_DD.cpp, src/modules/hydrology_longterm/SNO_DD/api.cpp
+ 更新宏定义模块：
+ Hydrology_longterm - PI_MSM
+ Hydrology_longterm - SET_LM
+ Hydrology_longterm - SNO_DD
=> update macro definition

preprocess/soil_chem.py, preprocess/soil_param.py
土壤属性数据查找表（soil_properties_lookup.txt）中允许不同土壤层数不同，且缺失数据允许-9999补齐，由程序自动计算缺失数据。
详情请参考dianbu示例数据
=> add support to multi-soil layers

database/model_param_ini.txt, model_data/dianbu/model_dianbu_30m_longterm/config.fig, model_data/dianbu/model_dianbu_30m_longterm/file.out, preprocess/import_parameters.py, preprocess/post_process_taudem.py, preprocess/subbasin_delineation.py, preprocess/text.py, src/base/util/text.h, src/modules/erosion/MUSLE_AS/MUSLE_AS.cpp, src/modules/erosion/MUSLE_AS/MUSLE_AS.h, src/modules/erosion/MUSLE_AS/api.cpp
+ 修复预处理中汇流累积量计算Bug
+ MUSLE_AS模块完成更新，如新增depRatio作为DT_Single型输入参数，USLE_K为DT_Raster2D数据
@gaohr
=> MUSLE_AS测试完毕

README.md, model_data/Command.txt, model_data/dianbu/model_dianbu_30m_longterm/config.fig, preprocess/MeteorologicalDaily.py, preprocess/PrecipitationDaily.py, preprocess/config.py, preprocess/dianbu_30m_longterm_omp_gaohr.ini, preprocess/dianbu_30m_longterm_omp_shenf.ini, preprocess/dianbu_30m_longterm_omp_zhulj_win.ini, preprocess/dianbu_30m_longterm_omp_zhulj_winserver.ini, preprocess/import_bmp_scenario.py, preprocess/import_measurement.py, preprocess/import_parameters.py, preprocess/main.py, preprocess/radius.py, preprocess/util.py, src/modules/ecology/AET_PTH/AET_PriestleyTaylorHargreaves.h, src/modules/ecology/AET_PTH/api.cpp
多数情况下，模型的预处理不可能一次成功，往往需要多次修改，而并非每次修改都需要运行整个预处理流程，因此，SEIMS提供了预处理过程中的子程序的调用。
基本调用命令为：
```python
> python XXX.py -ini <configurationFile>.ini
```
目前比较常用的有：
+ main.py
+ MeteorologicalDaily.py
+ PrecipitationDaily.py
+ import_measurement.py
+ import_parameters.py
+ import_bmp_scenario.py
这样的调用方式，方便不同开发者在自己机器上的路径配置，我们只需要修改自己的`*.ini`配置文件即可！
@gaohr  @Shenfang1993
=> 更新预处理程序调用方式

doc/TODO.md, preprocess/soil_chem.py, src/base/util/text.h, src/modules/erosion/KinWavSed_OL/KinWavSed_OL.cpp, src/modules/erosion/KinWavSed_OL/KinWavSed_OL.h, src/modules/hydrology/IKW_OL/ImplicitKinematicWave.h, src/modules/nutrient/MINRL/NandPmi.cpp, src/modules/nutrient/MINRL/NandPmi.h, src/modules/nutrient/MINRL/api.cpp, src/modules/nutrient/NutrCH/NutrientCHRoute.cpp, src/modules/nutrient/NutrCH/NutrientChRoute.h, src/modules/nutrient/NutrCH/api.cpp, src/modules/nutrient/NutrMV/NutrientRemviaSr.cpp, src/modules/nutrient/NutrOL/NutrientOLRoute.cpp, src/modules/nutrient/NutrOL/NutrientOLRoute.h
=> Move the calculation of soil chemical properties into the module

src/base/util/text.h, src/modules/nutrient/NutrCH/NutrientChRoute.h, src/modules/nutrient/NutrCH/api.cpp
=> Add nutrient concentration at the watershed outlet

src/base/util/text.h, src/modules/nutrient/MINRL/NandPmi.cpp, src/modules/nutrient/MINRL/api.cpp, src/modules/nutrient/NutrCH/NutrientCHRoute.cpp, src/modules/nutrient/NutrMV/NutrientRemviaSr.cpp, src/modules/nutrient/NutrMV/api.cpp
=> little update

model_data/dianbu/model_dianbu_30m_longterm/file.out, src/base/module_setting/ModuleFactory.cpp, src/base/util/text.h, src/modules/ecology/AET_PTH/AET_PriestleyTaylorHargreaves.cpp, src/modules/ecology/AET_PTH/AET_PriestleyTaylorHargreaves.h, src/modules/ecology/AET_PTH/api.cpp, src/modules/ecology/BIO_EPIC/Biomass_EPIC.cpp, src/modules/ecology/BIO_EPIC/Biomass_EPIC.h, src/modules/ecology/BIO_EPIC/api.cpp, src/modules/ecology/MGT_SWAT/api.cpp, src/modules/nutrient/AtmDep/AtmosphericDeposition.cpp, src/modules/nutrient/AtmDep/AtmosphericDeposition.h, src/modules/nutrient/AtmDep/api.cpp, src/modules/nutrient/MINRL/NandPmi.cpp, src/modules/nutrient/MINRL/NandPmi.h, src/modules/nutrient/MINRL/api.cpp, src/modules/nutrient/NutrMV/NutrientRemviaSr.cpp, src/modules/nutrient/NutrMV/api.cpp, src/modules/nutrient/NutrOL/api.cpp
+ 1. Delete m_cellWidth, m_nSoilLayers, m_sol_z, which are useless
+ 2. Change m_wshd_rno3 to store nitrate from rainfall of current day
+ 3. Remove output of m_sol_no3, which is redundant and unnecessary
+ 1. Change m_sol_cov and m_sol_rsd as AddInput from BIO_EPIC module
+ 2. Change m_wshd_dnit etc. variables to store the statistics values of the current day
+ 3. m_hmntl etc. variables should be DT_Raster1D rather than DT_Single since they are soil profile values in cell
+ 1. Add m_sol_rsdin as AddParameter and add the initialization of m_sol_cov and m_sol_rsd
@gaohr
=> Review nutrient and ecology modules

model_data/dianbu/model_dianbu_30m_longterm/config.fig, model_data/dianbu/model_dianbu_30m_longterm/file.out, preprocess/delta_s.py, preprocess/import_parameters.py, src/base/data/clsReach.cpp, src/base/data/clsSubbasin.cpp, src/base/data/clsSubbasin.h, src/base/module_setting/ModuleFactory.cpp, src/base/module_setting/ModuleFactory.h, src/base/module_setting/PrintInfo.cpp, src/base/module_setting/PrintInfo.h, src/base/module_setting/SettingsOutput.cpp, src/base/util/MetadataInfo.cpp, src/base/util/MetadataInfoConst.h, src/base/util/SimulationModule.h, src/base/util/text.h, src/base/util/util.cpp, src/main/ModulesIOList/ModulesIOList.cpp, src/main/main_omp/ModelMain.cpp, src/main/main_omp/ModelMain.h, src/main/main_omp/invoke.cpp, src/modules/hydrology_longterm/GWA_RE/ReservoirMethod.cpp, src/modules/hydrology_longterm/GWA_RE/ReservoirMethod.h, src/modules/hydrology_longterm/GWA_RE/api.cpp, src/modules/hydrology_longterm/SOL_WB/SOL_WB.cpp, src/modules/hydrology_longterm/SOL_WB/SOL_WB.h, src/modules/hydrology_longterm/SOL_WB/api.cpp, src/modules/hydrology_longterm/SOL_WB/subbasin.h
+ 增加clsSubbasins和Subbasin类，用于存放子流域尺度统计参数
+ 增加DT_Subbasin作为数据类型进行AddParameter设置，以避免多个模块重复计算（重复计算子流域个数、子流域栅格索引等）
+ 按照目前框架基本重新组织了GWA_RE及SOL_WB模块
=> GWA_RE及SOL_WB调试

model_data/dianbu/data_prepare/management/plant_management.txt, src/base/bmps/BMPPlantMgtFactory.cpp, src/base/bmps/BMPPlantMgtFactory.h, src/modules/ecology/BIO_EPIC/Biomass_EPIC.cpp, src/modules/ecology/MGT_SWAT/managementOperation_SWAT.cpp, src/modules/ecology/MGT_SWAT/managementOperation_SWAT.h, src/modules/nutrient/MINRL/NandPmi.cpp
=> BIO_EPIC和MGT_SWAT，bug修复

src/base/bmps/BMPPointSourceFactory.cpp, src/base/bmps/BMPPointSourceFactory.h, src/base/bmps/Scenario.h, src/base/data/clsSubbasin.cpp, src/base/util/SimulationModule.h, src/modules/ecology/MGT_SWAT/managementOperation_SWAT.cpp, src/modules/hydrology_longterm/MUSK_CH/MUSK_CH.cpp, src/modules/hydrology_longterm/MUSK_CH/MUSK_CH.h, src/modules/hydrology_longterm/MUSK_CH/api.cpp, src/modules/test/IO_TEST/IO_test.h
=> 添加点源污染物输入 MUSK_CH

database/model_param_ini.txt, model_data/dianbu/model_dianbu_30m_longterm/file.out, preprocess/gen_subbasins.py, preprocess/import_parameters.py, src/base/data/clsReach.cpp, src/base/util/text.h, src/base/util/util.cpp, src/base/util/util.h, src/main/functionTest/main.cpp, src/main/main_omp/ModelMain.cpp, src/modules/erosion/MUSLE_I30/MUSLE_I30.cpp, src/modules/erosion/SEDR_VCD/SEDR_VCD.cpp, src/modules/erosion/SEDR_VCD/SEDR_VCD.h, src/modules/erosion/SEDR_VCD/api.cpp, src/modules/hydrology_longterm/MUSK_CH/MUSK_CH.cpp, src/modules/hydrology_longterm/MUSK_CH/MUSK_CH.h, src/modules/hydrology_longterm/SSR_DA/SSR_DA.cpp, src/modules/hydrology_longterm/SSR_DA/SSR_DA.h, src/modules/hydrology_longterm/SSR_DA/api.cpp, src/modules/nutrient/MINRL/NandPmi.cpp, src/modules/nutrient/NutrCH_QUAL2E/NutrCH_QUAL2E.cpp, src/modules/nutrient/NutrCH_QUAL2E/NutrCH_QUAL2E.h, src/modules/nutrient/NutrCH_QUAL2E/api.cpp
=> 调试NutrCH_QUAL2E模块

CMakeLists.txt, src/base/bmps/BMPArealSourceFactory.cpp, src/base/bmps/BMPArealSourceFactory.h, src/base/bmps/PlantManagementOperation.h, src/base/bmps/Scenario.cpp, src/base/bmps/Scenario.h, src/base/data/InputStation.h, src/base/data/Measurement.h, src/base/data/MongoUtil.h, src/base/data/NotRegularMeasurement.cpp, src/base/data/NotRegularMeasurement.h, src/base/data/RegularMeasurement.h, src/base/data/clsSubbasin.h, src/base/module_setting/ModuleFactory.h, src/base/module_setting/PrintInfo.cpp, src/base/module_setting/PrintInfo.h, src/base/module_setting/SettingsInput.h, src/base/util/ModelException.h, src/base/util/util.cpp, src/base/util/util.h, src/base/util/utils.cpp, src/base/util/utils.h, src/main/main_omp/ModelMain.cpp, src/main/main_omp/ModelMain.h, src/modules/hydrology/CH_DW/DiffusiveWave.h, src/modules/management/PLTMGT_SWAT/api.cpp, src/modules/management/PLTMGT_SWAT/managementOperation_SWAT.cpp, src/modules/management/PLTMGT_SWAT/managementOperation_SWAT.h, src/modules/nutrient/NutrGW/NutrientinGroundwater.h
+ 在util模块中定义了TimeCounting()函数用于Windows和Linux下程序计时，因为之前用的Clock()函数在两个平台下计时差距很大，现在6线程下，windows和linux差不多了，分别为51秒，80秒
+ 参照这个博客调试了Linux下段错误[Segmentation Fault]
http://blog.csdn.net/acs713/article/details/14456187， 其实就是变量声明和初始化的错误
+ 完善了PLTMGT_SWAT代码，修复bug
+ Windows和Linux下结果依然不一致，但是结果趋势一致，肯定还是代码哪里出错了。
+ 明天， 我打算先把3个小流域的数据库都建好，然后把管理措施数据整理好。
+ 继续调BUG，BUG，BUG。。。。
(>﹏<。)～……
以上。
@gaohr  @liujunzhi321 @Shenfang1993
=> PLTMGT_SWAT模块Bug修复以及其他一些问题

model_data/Command.txt, preprocess/cpp_src/grid_layering/Data.cpp, preprocess/cpp_src/grid_layering/FlowInOut.cpp, preprocess/cpp_src/grid_layering/LayeringFromOutlet.cpp, preprocess/cpp_src/grid_layering/LayeringFromSource.cpp, preprocess/cpp_src/grid_layering/main.cpp, preprocess/gen_subbasins.py
连续运行3个小流域的预处理之后，grid_layering在第一个运行中结果正确，后面2个的FLOWOUT_INDEX_D8没有导入到MongoDB。
我检查了一下代码的内存释放，DEBUG模式下多次运行导入数据没问题，但是RELEASE模式下，依然存在问题。不知道为什么。
另外，三个小流域现在都能跑起来了。
BMP设置尚未完成
=> grid_layering存在bug

model_data/Command.txt, model_data/dianbu/model_dianbu2_30m_longterm/file.out, model_data/dianbu/model_dianbu3_30m_longterm/file.out, model_data/dianbu/model_dianbu_30m_longterm/file.out, preprocess/dianbu2_30m_longterm_omp_dgpm.ini, preprocess/dianbu2_30m_longterm_omp_zhulj_win.ini, preprocess/dianbu3_30m_longterm_omp_dgpm.ini, preprocess/dianbu3_30m_longterm_omp_zhulj_win.ini, src/main/main_omp/ModelMain.cpp
+ 如果在file.out中定义了当前模块没有的输出变量，则在模型构建时，将其删去，且不抛出异常，以保证模型正常运行
=> 修正对输出条目的抛出异常操作逻辑

model_data/dianbu/model_dianbu2_30m_longterm/config.fig, src/modules/ecology/AET_PTH/AET_PriestleyTaylorHargreaves.cpp, src/modules/ecology/BIO_EPIC/Biomass_EPIC.cpp, src/modules/ecology/BIO_EPIC/api.cpp, src/modules/hydrology_longterm/MUSK_CH/MUSK_CH.cpp, src/modules/hydrology_longterm/PER_PI/PER_PI.cpp, src/modules/hydrology_longterm/PER_PI/PER_PI.h, src/modules/management/NPSMGT/NonPointSource_Management.cpp, src/modules/management/PLTMGT_SWAT/api.cpp, src/modules/management/PLTMGT_SWAT/managementOperation_SWAT.cpp, src/modules/management/PLTMGT_SWAT/managementOperation_SWAT.h, src/modules/nutrient/AtmDep/AtmosphericDeposition.cpp, src/modules/nutrient/MINRL/NandPmi.cpp, src/modules/nutrient/NutrCH_QUAL2E/NutrCH_QUAL2E.cpp, src/modules/nutrient/NutrGW/NutrientinGroundwater.cpp, src/modules/nutrient/NutrMV/NutrientRemviaSr.cpp
=> finding bugs

src/modules/nutrient/NutrCH_QUAL2E/NutrCH_QUAL2E.cpp, src/modules/nutrient/NutrCH_QUAL2E/NutrCH_QUAL2E.h, src/modules/nutrient/NutrGW/NutrientinGroundwater.cpp, src/modules/nutrient/NutrMV/NutrientRemviaSr.cpp
+ 将CBOD转COD的相关参数（**cod_n**, **cod_k**）放在数据库中作为可调参数
=> update paramerters in COD calculation

src/base/util/text.h, src/modules/ecology/BIO_EPIC/Biomass_EPIC.cpp, src/modules/hydrology_longterm/MUSK_CH/MUSK_CH.cpp, src/modules/hydrology_longterm/MUSK_CH/MUSK_CH.h, src/modules/management/PLTMGT_SWAT/managementOperation_SWAT.cpp, src/modules/nutrient/NutrCH_QUAL2E/NutrCH_QUAL2E.cpp, src/modules/nutrient/NutrGW/NutrientinGroundwater.cpp, src/modules/nutrient/NutrMV/NutrientRemviaSr.cpp, src/modules/nutrient/NutrMV/NutrientRemviaSr.h, src/modules/nutrient/NutrMV/api.cpp
+ MUSK_CH中初始化河道水量的时候，混淆了m_chWTDepth和m_chDepth，导致debug和Release结果不一致
+ PLTMGT_SWAT中某个函数应该用break跳出for循环，错用了return结束该函数
+ 整理了NUTRMV模块中NitrateLoss函数，并将COD等计算剥离成SubbasinWaterQuality函数
=> bug fixed in MUSK_CH and PLTMGT_SWAT module

postprocess/hydroPlot_main.py, src/modules/nutrient/NutrSed/SurrunoffTransfer.cpp, src/modules/nutrient/NutrSed/SurrunoffTransfer.h
修复模块NUTRSED中的BUGs
+ 每天流入河道的吸附态养分初始化为0
+ 更正栅格面积计算的错误
=> fix bugs in NUTRSED

postprocess/RelativeImportModules.py, postprocess/config.py, postprocess/hydroPlot.py
https://pypi.python.org/packages/b8/1b/02efe53150500722d1b5bbe3d9dd5a417fe07df05566595cf9114ced3c39/pathlib2-2.1.0-py2.py3-none-any.whl#md5=4d3c9e9e09a470f6274885f16be05a78
=> support relative imports in python

postprocess/hydroPlot.py
=> 修改后处理程序中柱状图位置

preprocess/TauDEM.py, scenario_analysis/scenario.py, scenario_analysis/userdef.py
=> 采用uuid模块产生随机数作为新的情景ID
